name: HarDorm
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_multiselect: ^0.0.1
  carousel_slider: ^1.3.0
  expandable_text: ^0.1.0
  google_maps_flutter: ^0.5.24+1
  flutter_launcher_icons: ^0.7.5
  flutter_rating_bar: ^3.2.0+1
  provider: ^4.3.3
  http: ^0.12.2
  date_range_picker: ^1.0.3
  intl: 0.15.7
  flutter_tindercard: ^0.2.0
  line_icons: ^1.3.2
  # flutter_svg: ^0.19.3
  flutter_custom_clippers: ^1.1.2




dev_dependencies:
  flutter_test:
    sdk: flutter



flutter_launcher_icons:
    path: ../

flutter_icons:
  image_path_android: "assets/logo/app_icon1.png"
  image_path_ios: "assets/logo/app_icon1.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/logo/app_icon1.png"
  adaptive_icon_foreground: "assets/logo/app_icon1.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/top.png
    - assets/bottom.png
    - icon/google_logo.png
    - icon/twitter_logo.png
    - icon/facebook_logo.png
    - assets/3.png
    - assets/person.png
    - picHor/matt-reames-aFk1RLZgJTs-unsplash.jpg
    - picHor/Hor1.jpg
    - picHor/Hor2.jpg
    - picHor/Hor3.jpg
    - picHor/Hor4.jpg
    - picHor/Hor5.jpg
    - room/room1.jpg
    - room/room2.jpg
    - room/room3.jpg
    - room/room4.jpg
    - room/room5.jpg
    - room/room6.jpg
    - room/room7.jpg
    - assets/Avatar/chun1.jpg
    - assets/components/Line.png
    - assets/Avatar/battle.jpg
    - assets/Avatar/changge.jpg
    - assets/Avatar/jim.jpg
    - assets/Avatar/john.jpg
    - assets/Avatar/liaruge.jpg
    - assets/Avatar/linglingqi.jpg
    - assets/Avatar/paul.jpg
    - assets/Avatar/ten.jpg
    - assets/Avatar/tommy.jpg
    - assets/Avatar/farmer.jpg
    - assets/Avatar/hbd.jpg
    - assets/Avatar/maple.jpg
    - assets/Avatar/tree.jpg
    - assets/Avatar/mountain.jpg
    - assets/components/information.png
    - assets/components/telephone.png
    - assets/components/underline.png
    - assets/components/topProfile1.png
    - assets/components/success.png
    - assets/components/friends.png
    - assets/components/friends_active.png
    - assets/components/heartLike.png
    - assets/components/heartLikeActive.png
    - assets/components/close.png
    - assets/components/heart.png
    - assets/components/refresh.png
    
    


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  fonts:
      - family: Poppins
        fonts:
          - asset: fonts/Poppins-Regular.ttf

      - family:   IconHardorm
        fonts:
          - asset: icon/IconHardorm.ttf
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
