/// Flutter icons IconHardorm
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconHardorm
///      fonts:
///       - asset: fonts/IconHardorm.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconHardorm {
  IconHardorm._();

  static const _kFontFam = 'IconHardorm';
  static const  _kFontPkg = null;

  static const IconData chatcircle = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i2097743_1 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double_quotes = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData review = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like__1_ = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electric = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_people_symbol = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fitness_facilities = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water_drops = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData route = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData find = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData terrace = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData garden = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData free_wifi = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shower = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cleaning_tools = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData elevator = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData air_conditioner = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swimmer = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData worldwide = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blanket__2_ = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blanket__1_ = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blanket = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telephone = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh_arrow = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bold_text_option = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData underlined_text = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData italicize_text = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData friends = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_arrow = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick_inside_circle = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
